{% set name = "google-cloud-dlp" %}
{% set version = "3.7.1" %}
{% set sha256 = "ab623792ef1fe79ad2250139a220edb50389158b463e39ab5bb86dad9f8130f5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.15.0
    - pytz >=2021.1

test:
  imports:
    - grpc
    - google.cloud.dlp
    - google.cloud.dlp_v2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-dlp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cloud Data Loss Prevention (DLP) API client library
  description: "Cloud Data Loss Prevention (DLP) API provides methods for detection, risk analysis, and de-identification of privacy-sensitive fragments in text, images, and Google Cloud Platform storage repositories.\nSee the [quick start guide](https://googleapis.dev/python/dlp/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dlp/latest/index.html
  dev_url: https://github.com/googleapis/python-dlp

extra:
  recipe-maintainers:
    - xylar
    - parthea
