{% set name = "google-cloud-dlp" %}
{% set version = "3.4.0" %}
{% set sha256 = "0b249fa87deb57f5c7107a7d5d303673590a6524a7f113fc95f87493f3328606" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=0.4.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.dlp
    - google.cloud.dlp_v2

about:
  home: https://github.com/googleapis/python-dlp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cloud Data Loss Prevention (DLP) API client library
  description: "Cloud Data Loss Prevention (DLP) API provides methods for detection, risk analysis, and de-identification of privacy-sensitive fragments in text, images, and Google Cloud Platform storage repositories.\nSee the [quick start guide](https://googleapis.dev/python/dlp/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dlp/latest/index.html
  dev_url: https://github.com/googleapis/python-dlp

extra:
  recipe-maintainers:
    - parthea
