{% set name = "google-cloud-dlp" %}
{% set version = "3.8.0" %}
{% set sha256 = "c62759ec4b5ec83505c715ce5e04a0e8e524ce52331209c031195e7616b4b3f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - proto-plus >=1.15.0,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev

test:
  imports:
    - grpc
    - google.cloud.dlp
    - google.cloud.dlp_v2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-dlp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cloud Data Loss Prevention (DLP) API client library
  description: "Cloud Data Loss Prevention (DLP) API provides methods for detection, risk analysis, and de-identification of privacy-sensitive fragments in text, images, and Google Cloud Platform storage repositories.\nSee the [quick start guide](https://googleapis.dev/python/dlp/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dlp/latest/index.html
  dev_url: https://github.com/googleapis/python-dlp

extra:
  recipe-maintainers:
    - xylar
    - parthea
